// <auto-generated />
using System;
using DonationSite.DataAccess.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DonationSite.DataAccess.EF.Migrations
{
    [DbContext(typeof(DonationSiteDataContext))]
    [Migration("20220131131114_inital")]
    partial class inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DonationSite.Core.Entities.Donate.Donate", b =>
                {
                    b.Property<int>("DonateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DonatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FKSiteID")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DonateID");

                    b.HasIndex("FKSiteID");

                    b.ToTable("Donate");

                    b.HasData(
                        new
                        {
                            DonateID = 1,
                            DonatorName = "Feredrick B ",
                            FKSiteID = 1,
                            Value = 20m
                        },
                        new
                        {
                            DonateID = 2,
                            DonatorName = "Kristopher E Smith",
                            FKSiteID = 1,
                            Value = 20m
                        },
                        new
                        {
                            DonateID = 3,
                            DonatorName = "Edwin E Walker",
                            FKSiteID = 1,
                            Value = 34m
                        },
                        new
                        {
                            DonateID = 4,
                            DonatorName = "Alma J Peterson",
                            FKSiteID = 1,
                            Value = 14.5m
                        },
                        new
                        {
                            DonateID = 5,
                            DonatorName = "Matt S Moore",
                            FKSiteID = 1,
                            Value = 40m
                        },
                        new
                        {
                            DonateID = 6,
                            DonatorName = "William P Young",
                            FKSiteID = 1,
                            Value = 10m
                        },
                        new
                        {
                            DonateID = 7,
                            DonatorName = "Grace R Square",
                            FKSiteID = 2,
                            Value = 50m
                        },
                        new
                        {
                            DonateID = 8,
                            DonatorName = "Zandra N Sweeney",
                            FKSiteID = 2,
                            Value = 70m
                        },
                        new
                        {
                            DonateID = 9,
                            DonatorName = "Monte L Mosher",
                            FKSiteID = 2,
                            Value = 60m
                        },
                        new
                        {
                            DonateID = 10,
                            DonatorName = "Louis N Leon",
                            FKSiteID = 2,
                            Value = 30m
                        },
                        new
                        {
                            DonateID = 11,
                            DonatorName = "Chris K Thomas",
                            FKSiteID = 2,
                            Value = 80m
                        },
                        new
                        {
                            DonateID = 12,
                            DonatorName = "Corey K Bryson",
                            FKSiteID = 2,
                            Value = 500m
                        },
                        new
                        {
                            DonateID = 13,
                            DonatorName = "Dennis A Schultz",
                            FKSiteID = 2,
                            Value = 47m
                        },
                        new
                        {
                            DonateID = 14,
                            DonatorName = "Kam R Northington",
                            FKSiteID = 2,
                            Value = 52m
                        },
                        new
                        {
                            DonateID = 15,
                            DonatorName = "Mary R Delvalle",
                            FKSiteID = 2,
                            Value = 69m
                        },
                        new
                        {
                            DonateID = 16,
                            DonatorName = "Martha J Wright",
                            FKSiteID = 2,
                            Value = 85m
                        },
                        new
                        {
                            DonateID = 17,
                            DonatorName = "Nickolas D Steiner",
                            FKSiteID = 2,
                            Value = 85m
                        },
                        new
                        {
                            DonateID = 18,
                            DonatorName = "Josephine M Delarosa",
                            FKSiteID = 2,
                            Value = 78m
                        },
                        new
                        {
                            DonateID = 19,
                            DonatorName = "Ernest V Stocking",
                            FKSiteID = 3,
                            Value = 35m
                        },
                        new
                        {
                            DonateID = 20,
                            DonatorName = "Todd L Rodriquez",
                            FKSiteID = 3,
                            Value = 36m
                        },
                        new
                        {
                            DonateID = 21,
                            DonatorName = "Graham S Rhodes",
                            FKSiteID = 3,
                            Value = 48m
                        },
                        new
                        {
                            DonateID = 22,
                            DonatorName = "Walter C Wright",
                            FKSiteID = 4,
                            Value = 42m
                        },
                        new
                        {
                            DonateID = 23,
                            DonatorName = "Sandra M Miles",
                            FKSiteID = 4,
                            Value = 19m
                        },
                        new
                        {
                            DonateID = 24,
                            DonatorName = "Keith J Spencer",
                            FKSiteID = 5,
                            Value = 44m
                        },
                        new
                        {
                            DonateID = 25,
                            DonatorName = "Joel A McDougal",
                            FKSiteID = 6,
                            Value = 66m
                        },
                        new
                        {
                            DonateID = 26,
                            DonatorName = "Lisa H Dudley",
                            FKSiteID = 7,
                            Value = 22m
                        },
                        new
                        {
                            DonateID = 27,
                            DonatorName = "Roderick B French",
                            FKSiteID = 7,
                            Value = 28m
                        },
                        new
                        {
                            DonateID = 28,
                            DonatorName = "Emily P Aultman",
                            FKSiteID = 7,
                            Value = 90m
                        },
                        new
                        {
                            DonateID = 29,
                            DonatorName = "Joanna E Merritt",
                            FKSiteID = 10,
                            Value = 159m
                        },
                        new
                        {
                            DonateID = 30,
                            DonatorName = "George K Harris",
                            FKSiteID = 10,
                            Value = 50.5m
                        },
                        new
                        {
                            DonateID = 31,
                            DonatorName = "Bart T Aguilar",
                            FKSiteID = 10,
                            Value = 74m
                        },
                        new
                        {
                            DonateID = 32,
                            DonatorName = "Charles E Bowles",
                            FKSiteID = 10,
                            Value = 70m
                        });
                });

            modelBuilder.Entity("DonationSite.Core.Entities.Site.Site", b =>
                {
                    b.Property<int>("SiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiteID");

                    b.ToTable("Site");

                    b.HasData(
                        new
                        {
                            SiteID = 1,
                            CreatedDateTime = new DateTime(2022, 1, 31, 16, 41, 13, 611, DateTimeKind.Local).AddTicks(1731),
                            Name = "Google Co.",
                            URL = "www.google.com"
                        },
                        new
                        {
                            SiteID = 2,
                            CreatedDateTime = new DateTime(2022, 1, 31, 16, 41, 13, 617, DateTimeKind.Local).AddTicks(1942),
                            Name = "Facebook Co.",
                            URL = "www.Facebook.com"
                        },
                        new
                        {
                            SiteID = 3,
                            CreatedDateTime = new DateTime(2022, 1, 31, 16, 41, 13, 617, DateTimeKind.Local).AddTicks(2026),
                            Name = "Amazon Co.",
                            URL = "www.Amazon.com"
                        },
                        new
                        {
                            SiteID = 4,
                            CreatedDateTime = new DateTime(2022, 1, 31, 16, 41, 13, 617, DateTimeKind.Local).AddTicks(2042),
                            Name = "MCI Co.",
                            URL = "www.MCI.com"
                        },
                        new
                        {
                            SiteID = 5,
                            CreatedDateTime = new DateTime(2022, 1, 31, 16, 41, 13, 617, DateTimeKind.Local).AddTicks(2049),
                            Name = "Alexa Co.",
                            URL = "www.Alexa.com"
                        },
                        new
                        {
                            SiteID = 6,
                            CreatedDateTime = new DateTime(2022, 1, 31, 16, 41, 13, 617, DateTimeKind.Local).AddTicks(2056),
                            Name = "Linkedin Co.",
                            URL = "www.Linkedin.com"
                        },
                        new
                        {
                            SiteID = 7,
                            CreatedDateTime = new DateTime(2022, 1, 31, 16, 41, 13, 617, DateTimeKind.Local).AddTicks(2062),
                            Name = "Microsoft Co.",
                            URL = "www.Microsoft.com"
                        },
                        new
                        {
                            SiteID = 8,
                            CreatedDateTime = new DateTime(2022, 1, 31, 16, 41, 13, 617, DateTimeKind.Local).AddTicks(2068),
                            Name = "Mozilla Co.",
                            URL = "www.Mozilla.com"
                        },
                        new
                        {
                            SiteID = 9,
                            CreatedDateTime = new DateTime(2022, 1, 31, 16, 41, 13, 617, DateTimeKind.Local).AddTicks(2075),
                            Name = "Blizzard Co.",
                            URL = "www.Blizzard.com"
                        },
                        new
                        {
                            SiteID = 10,
                            CreatedDateTime = new DateTime(2022, 1, 31, 16, 41, 13, 617, DateTimeKind.Local).AddTicks(2083),
                            Name = "Activision Co.",
                            URL = "www.Activision.com"
                        });
                });

            modelBuilder.Entity("DonationSite.Core.Entities.Donate.Donate", b =>
                {
                    b.HasOne("DonationSite.Core.Entities.Site.Site", "Site")
                        .WithMany()
                        .HasForeignKey("FKSiteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });
#pragma warning restore 612, 618
        }
    }
}
