// <auto-generated />
using System;
using DonationSite.DataAccess.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DonationSite.DataAccess.EF.Migrations
{
    [DbContext(typeof(DonationSiteDataContext))]
    partial class DonationSiteDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DonationWebsite.Core.Entities.Donate", b =>
                {
                    b.Property<int>("DonateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DonatorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SitesSiteID")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DonateID");

                    b.HasIndex("SitesSiteID");

                    b.ToTable("Donate");
                });

            modelBuilder.Entity("DonationWebsite.Core.Entities.Site", b =>
                {
                    b.Property<int>("SiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiteID");

                    b.ToTable("Site");
                });

            modelBuilder.Entity("DonationWebsite.Core.Entities.Donate", b =>
                {
                    b.HasOne("DonationWebsite.Core.Entities.Site", "Sites")
                        .WithMany("Donates")
                        .HasForeignKey("SitesSiteID");

                    b.Navigation("Sites");
                });

            modelBuilder.Entity("DonationWebsite.Core.Entities.Site", b =>
                {
                    b.Navigation("Donates");
                });
#pragma warning restore 612, 618
        }
    }
}
